sudo: required
language: python
python:
  - "3.6"

addons:
  apt:
    packages:
      - python-pip
      - python-dev

services:
  - docker

before_install:
  - deactivate
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-ce
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart

install:
  - sudo pip install docker-py
  - sudo apt-get install -y sshpass software-properties-common python-software-properties
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible
  - ansible-galaxy install -r test/requirements.yml -p test/roles/

script:
  make test
